services:
  go-db:
    container_name: go-db
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "3306:3306"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}